[package]
name = "pott_core"
version = "0.1.0"
edition = "2021"
description = "TOTP dcrypter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.6"
